# Generated by Django 5.0.2 on 2024-02-16 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_access_file_alter_access_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
